sudo: required
language: ruby
rvm:
- 2.3.1
env:
  matrix:
  - OS_TYPE=centos OS_VERSION=6
  global:
  - WORKDIR=/source
  - VERSION=2.3.1
  - secure: eQJUeGtuSCXI7A3pJAB73cr8CK4N05ZKGHk8SLedWgwTvbxWeuez0CrL42TEJs5Swyk/MGhYLqXxxBqqrMjQbMUqgObBGqg87I5nLal4RbeFTSqEvorZZ4xeoMx7q0uVlLXkqX6ho3xM7uYXN7BOkNNJm5yNUkDKKi8BZnTYMuXjC2ModHsCy9c5wQYIVYvuh27fG/wy+NJGe1nnakWFn4m8Quu4Q2zbzIww22YkFaMX0j/EDmfd2UcjgkJlJ0DYeLwXXQateMyDO7qwHEVxGKSCKCvU4GiFdyIqXAsz0nFKTC+WGeKGycKM85vJmHzqo0CIxbddG3HQsukpaBFz5AkbsGXVth8shU++0rZ7Mpr0FWQYsTbEg4gRFtQvfRSlaQ+AL+nLMptx2TUbCELyPdbwEfld8oBLKXyH2V1EXMiALBSbfO4h23QPw1eZ95G+VHmADTpKR5j/fyycEMdi4BQke50OcvTGr0VxtYj2gXf21Ad3h4TPk1+oefmDvkO+eYxLSwraQMQyvrmHqxm50cXGMlwGXoqSzjQ1cwqyM9QbmgslL7k3PXb6Fa4uUUezBrgAZMdub/msEHWv/HVod4xufLlFHpN6jRgQ7J6ZcATADc0vRENC6xl2ams4ivRHuxGMmhLPiyEJSste4MqXU7kfexOTTYvOuues3wE6pUs=
services:
- docker
before_install: 
- echo $passphrase | gpg --passphrase-fd 0 rpm-signing.tar.asc
- tar xf rpm-signing.tar
- mkdir -p $(pwd)/.gnupg && chmod 700 $(pwd)/.gnupg
- gpg --no-default-keyring --secret-keyring .gnupg/secring.gpg --keyring .gnupg/pubring.gpg
  --import rpm-signing.asc
install:
- docker build -t beol:rpm-build .
before_script:
- mkdir -p $(pwd)/rpmbuild/SOURCES
- curl -# -L -o $(pwd)/rpmbuild/SOURCES/ruby-${VERSION}.tar.gz https://cache.ruby-lang.org/pub/ruby/2.3/ruby-${VERSION}.tar.gz
script:
- test "${TRAVIS_BRANCH}" = "master" && RELEASE_VERSION="`date +%Y%m%d%H%M`.`git rev-parse
  --short ${TRAVIS_BRANCH}`" || RELEASE_VERSION=""
- docker run --rm=true -v $(pwd):${WORKDIR}:rw -e "RELEASE_VERSION=${RELEASE_VERSION}"
  beol:rpm-build bash ${WORKDIR}/build.sh
- docker run --rm=true -v $(pwd):${WORKDIR}:rw centos:${OS_TYPE}${OS_VERSION} bash
  -c "find /source -name \"*.rpm\" -type f | xargs -I{} yum -y localinstall {}"
